version: '3'
services:
  db:
    image: mysql:8.0.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BDDProjetDataBateau
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./data:/docker-entrypoint-initdb.d

  nodejs:
    image: ghcr.io/srthibaultp/projetbateau:latest
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  mysql-data: